version: '2'
services:
  registry:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE
      - REGISTRY_HTTP_TLS_KEY
      - REGISTRY_AUTH
      - REGISTRY_AUTH_HTPASSWD_PATH
      - REGISTRY_AUTH_HTPASSWD_REALM
      - PRIVATEREGISTRY_CONF
      - PRIVATEREGISTRY_TLS
      - PRIVATEREGISTRY_AUTH_ENTRIES
    volumes:
      - registry-data:/var/lib/registry


volumes:
  registry-data:
    driver: local
