version: '3.4'
services:
  app:
    networks:
      - servicenet
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
          cpus: '0.1'
      restart_policy:
        condition: any
        delay: 5s
        window: 120s


volumes:
    docker-registry-registry-data:
        external:
            name: docker-registry-registry-data


networks:
  servicenet:
    driver: overlay
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.32.48/28
